name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


env:
  PORT: "3001"
  SECRET: ${{ secrets.SECRET }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Backend dependencies
        run: |
          cd ./backend
          npm ci
      - name: Install Frontend dependencies
        run: |
          cd ./frontend
          npm ci
      - name: Check style
        run: npm run lint
      - name: Tests frontend
        run: npm run test:frontend
      - name: Tests backend
        run: npm run test:backend
        env:
          PORT: "3001"
          SECRET: ${{ secrets.SECRET }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
      - name: Start Server for Cypress Tests
        run: npm run start:server &
        env:
          PORT: "6969"
          SECRET: ${{ secrets.SECRET }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
      - name: Cypress tests 
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
      - name: Build
        if: success()
        run: npm run build
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:  
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DEFAULT_BRANCH: main
  notify_discord:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Discord notify success
        if: ${{ success() && github.event_name == 'push' }}
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with: 
          args: |
            "✅ Deployment was sucessful"

      - name: Discord notify error
        if: ${{ failure() && github.event_name == 'push' }} 
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with: 
          args: |
            "❌ Deployment failed"
